version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=root
      - MONGODB_ENDPOINT=mongodb:27017

  redis:
    image: "redis:alpine"
  mongodb:
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=records
